---
title: Data Science in Education Using R
author: Ryan Estrellado
date: '2020-07-04'
slug: data-science-in-education-using-r
categories: []
tags: []
summary: 'I wrote a book with some really awesome people. Data Science in Education Using R is an open source book about learning R and data science in the education field. The print version is now available for pre-order and will be available from Routledge in October 2020.'
authors: []
external_link: ''
image:
  caption: ''
  focal_point: ''
  preview_only: no
url_code: ''
url_pdf: ''
url_slides: ''
url_video: ''
slides: ''
---

I'm excited to announce that *Data Science in Education Using R* is now available for pre-order on [Amazon](https://www.amazon.com/s?k=data+science+in+education+using+r&crid=3VV9C2C3NGGMY&sprefix=data+science+in+education%2Caps%2C204&ref=nb_sb_ss_i_1_25) and [Routledge](https://www.routledge.com/search?kw=data+science+in+education+using+R)! The print version will be available from Routledge in October 2020. 

And as always, you can read Data Science in Education for Using R [here](https://datascienceineducation.com). 

## Book Description 

Data Science in Education Using R is the go-to reference for learning data science in the education field. The book answers questions like: What does a data scientist in education do? How do I get started learning R, the popular open source statistical programming language? And what does a data analysis project in education look like?

If you’re just getting started with R in an education job, this is the book you’ll want with you. This book gets you started with R by teaching the building blocks of programming that you’ll use many times in your career. The book takes a "learn by doing" approach and offers eight analysis walkthroughs that show you a data analysis from start to finish, complete with code for you to practice with. The book finishes with how to get involved in the data science community and how to integrate data science in your education job.

This book will be an essential resource for education professionals and researchers looking to increase their data analysis skills as part of their professional and academic development.

## Authors 

**Ryan A. Estrellado** has served public schools for over seventeen years as a school psychologist and administrator.

**Emily A. Freer** is the Director of Educational Development and Assessment at the Marquette University School of Dentistry.

**Jesse Mostipak** is the Community Advocate for Kaggle, and has worked both as a high school science teacher and lead data scientist within education non-profits.

**Joshua M. Rosenberg** is an Assistant Professor of STEM Education at the University of Tennessee, Knoxville.

**Isabella C. Velásquez** is a data analyst committed to nonprofit work with the goal of reducing racial and socioeconomic inequities

## Reviews

"The authors have provided the definitive guide to the topic. The combination of theory and hands-on practical tutorials make this an invaluable resource for the growing fields of learning analytics and educational data science." *- Mark Warschauer, Professor of Education and Informatics at the University of California, Irvine*

"This book is a clear, compelling guide for real-world practitioners who are ready to use modern tools of data science in the education domain. The effective data analysis content would benefit almost anyone getting started with data today, but these authors' thoughtful, focused handling of the specific issues involved in working with education data sets it apart from most introductory data science books." *- Julia Silge, Software Engineer at RStudio*

"There are many resources for learning how to analyze education data. But what has long been missing is an inclusive and pedagogically refined resource on how to leverage modern data science principles, workflows, and tools. Data Science in Education using R fills this massive gap and more. It will be the go to resource for the next generation of data driven education professionals. And is a beautiful exposition of how to responsibly work with data from the real, messy, world." *- Dustin Tingley, Deputy Vice Provost for Advances in Learning at Harvard University*

"Data Science in Education Using R provides a wide menu of resources for individuals in education who wish to both learn R and think more deeply about their relationship to data. The book provides both practical guidance through worked examples and discussions of relevant theory and past research. That the book is written by authors who have varied research and practice positions lends itself to its broad-ranging appeal." *- Teomara (Teya) Rutherford, Assistant Professor of Learning Sciences, University of Delaware*

"Doing data science in education is an interdisciplinary endeavor. If you are a teacher, an administrator, or an educational researcher who's looking for a theory-informed, practice-oriented, and equity-minded introduction to educational data science, no need to look further than this book. It will help you unleash your data science "superpower," turbocharge your practice, and make real-world changes in your organization." *- Bodong Chen, Associate Professor and Co-Director of Learning Informatics Lab at the University of Minnesota*